src/Entity/Mda.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;


/**
 * @ORM\Entity(repositoryClass="App\Repository\MdaRepository")
 */
class Mda
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $mda_code;

    /**
     * @ORM\Column(type="string")
     */
    private $name;

    /**
     * @ORM\Column(type="string",
     *     nullable = true
     *     )
     */
    private $email;

    /**
     * @ORM\Column(type="text", nullable = true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", nullable = true)
     */
    private $phone;

    /**
     * @ORM\Column(type="boolean", nullable = true)
     */
    private $not_attended;

    /**
     * @ORM\Column(type="string", nullable = true)
     */
    private $top_official_designation;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getMdaCode()
    {
        return $this->mda_code;
    }

    /**
     * @param mixed $mda_code
     */
    public function setMdaCode($mda_code): void
    {
        $this->mda_code = $mda_code;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name): void
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email): void
    {
        $this->email = $email;
    }

    /**
     * @return mixed
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * @param mixed $address
     */
    public function setAddress($address): void
    {
        $this->address = $address;
    }

    /**
     * @return mixed
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * @param mixed $phone
     */
    public function setPhone($phone): void
    {
        $this->phone = $phone;
    }

    /**
     * @return mixed
     */
    public function getTopOfficialDesignation()
    {
        return $this->top_official_designation;
    }

    /**
     * @param mixed $top_official_designation
     */
    public function setTopOfficialDesignation($top_official_designation): void
    {
        $this->top_official_designation = $top_official_designation;
    }

    /**
     * @return mixed
     */
    public function getNotAttended()
    {
        return $this->not_attended;
    }

    /**
     * @param mixed $not_attended
     */
    public function setNotAttended($not_attended)
    {
        $this->not_attended = $not_attended;
    }


    public function __construct()
    {
        $this->participants_allowed = new ArrayCollection();

    }

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ParticipantsAllowed", mappedBy="mda_id")
     */
    private $participants_allowed;


    /**
     * @return Collection|ParticipantsAllowed[]
     */
    public function getParticipantsAllowed()
    {
        return $this->participants_allowed;
    }

}

src/Entity/Training.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrainingRepository")
 */
class Training
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $title;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string")
     */
    private $venue;

    /**
     * @ORM\Column(type="time")
     */
    private $time;

    /**
     * @ORM\Column(type="string")
     */
    private $training_code;

    /**
     * @ORM\Column(type="integer")
     */
    private $registration_fee;

    /**
     * @ORM\Column(type="integer")
     */
    private $individual_amount;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $refresher_individual_amount;

    /**
     * @ORM\Column(type="integer")
     */
    private $extra_personnel_amount;

    /**
     * @ORM\Column(type="integer")
     */
    private $individuals_per_mda;

    /**
     * @ORM\Column(type="integer")
     */
    private $parent_id;

    /**
     * @ORM\Column(type="text")
     */
    private $letter_content;

    /**
     * @ORM\Column(type="text")
     */
    private $refresher_letter_content;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param mixed $title
     */
    public function setTitle($title): void
    {
        $this->title = $title;
    }

    /**
     * @return mixed
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param mixed $date
     */
    public function setDate($date): void
    {
        $this->date = $date;
    }

    /**
     * @return mixed
     */
    public function getVenue()
    {
        return $this->venue;
    }

    /**
     * @param mixed $venue
     */
    public function setVenue($venue): void
    {
        $this->venue = $venue;
    }

    /**
     * @return mixed
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * @param mixed $time
     */
    public function setTime($time): void
    {
        $this->time = $time;
    }

    /**
     * @return mixed
     */
    public function getIndividualAmount()
    {
        return $this->individual_amount;
    }

    /**
     * @param mixed $individual_amount
     */
    public function setIndividualAmount($individual_amount): void
    {
        $this->individual_amount = $individual_amount;
    }

    /**
     * @return mixed
     */
    public function getExtraPersonnelAmount()
    {
        return $this->extra_personnel_amount;
    }

    /**
     * @param mixed $extra_personnel_amount
     */
    public function setExtraPersonnelAmount($extra_personnel_amount): void
    {
        $this->extra_personnel_amount = $extra_personnel_amount;
    }

    /**
     * @return mixed
     */
    public function getIndividualsPerMda()
    {
        return $this->individuals_per_mda;
    }

    /**
     * @param mixed $individuals_per_mda
     */
    public function setIndividualsPerMda($individuals_per_mda): void
    {
        $this->individuals_per_mda = $individuals_per_mda;
    }

    /**
     * @return mixed
     */
    public function getRegistrationFee()
    {
        return $this->registration_fee;
    }

    /**
     * @param mixed $registration_fee
     */
    public function setRegistrationFee($registration_fee): void
    {
        $this->registration_fee = $registration_fee;
    }

    /**
     * @return mixed
     */
    public function getLetterContent()
    {
        return $this->letter_content;
    }

    /**
     * @param mixed $letter_content
     */
    public function setLetterContent($letter_content): void
    {
        $this->letter_content = $letter_content;
    }

    /**
     * @return mixed
     */
    public function getRefresherLetterContent()
    {
        return $this->refresher_letter_content;
    }

    /**
     * @param mixed $refresher_letter_content
     */
    public function setRefresherLetterContent($refresher_letter_content)
    {
        $this->refresher_letter_content = $refresher_letter_content;
    }

    /**
     * @return mixed
     */
    public function getTrainingCode()
    {
        return $this->training_code;
    }

    /**
     * @param mixed $training_code
     */
    public function setTrainingCode($training_code)
    {
        $this->training_code = $training_code;
    }



    public function __construct()
    {
        $this->participants_allowed = new ArrayCollection();
        $this->invoices = new ArrayCollection();


    }

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ParticipantsAllowed", mappedBy="training_id")
     */
    private $participants_allowed;


    /**
     * @return Collection|ParticipantsAllowed[]
     */
    public function getParticipantsAllowed()
    {
        return $this->participants_allowed;
    }

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Invoice", mappedBy="training_id")
     */
    private $invoices;


    /**
     * @return Collection|Invoice[]
     */
    public function getInvoices()
    {
        return $this->invoices;
    }

    /**
     * @return mixed
     */
    public function getParentId()
    {
        return $this->parent_id;
    }

    /**
     * @param mixed $parent_id
     */
    public function setParentId($parent_id)
    {
        $this->parent_id = $parent_id;
    }

    /**
     * @return mixed
     */
    public function getRefresherIndividualAmount()
    {
        return $this->refresher_individual_amount;
    }

    /**
     * @param mixed $refresher_individual_amount
     */
    public function setRefresherIndividualAmount($refresher_individual_amount)
    {
        $this->refresher_individual_amount = $refresher_individual_amount;
    }


}

templates/pages/generate_letter.html.twig
{% extends 'access_base.html.twig' %}

{% block content %}

    <h2 class="page-header pt-4">Generate MDA letter</h2>
    <hr>

    {% include 'common/nav.html.twig' %}

    <div class="row pt-3 d-flex">

        <div class="col-lg-7 mx-auto">

            <div class="bg-dark p-3 mb-3 font-white border_radius">
                <p class="font-xs-2 mb-0 bottom_buffer font-weight-900 text-uppercase font-green">MDA</p>
                <h4>{{ mda }}</h4>

                {# <p class="font-xs-2 mb-0 mt-3 bottom_buffer font-weight-900 text-uppercase font-green">Contact information</p>
                 <p class="no_margin">{{ email }} • {{ phone }}</p>#}
            </div>

            <form action="{{ path('mda_letter') }}" method="POST">

                <div class="form-group">
                    <label>Select a training</label>
                    <select name="training" class="custom-select">
                        {% for training in trainings %}

                            <option value="{{ training.id }}">{{ training.title }}</option>

                            {% endfor %}
                    </select>
                </div>

                <div class="form-group">

                    <label>Training type</label> <br>
                    <input type="radio" class="custom-radio" value="New training" name="training_type"> New training
                    <input type="radio" class="custom-radio" value="Refresher training" name="training_type"> Refresher training

                </div>

                <hr>

                <div class="form-group">

                    <label>Email</label> <br>
                    <input type="text" class="form-control" name="email">

                </div>

                <div class="form-group">

                    <label>Phone</label> <br>
                    <input type="text" class="form-control" name="phone" onkeypress="return isNumber(event)">

                </div>

                <input type="hidden" name="mda" value="{{ mda }}">

                <button class="btn btn-block mt-3 btn-success"><i class="fa fa-file-text-o"></i> Generate Letter</button>

            </form>

        </div>

    </div>


{% endblock %}

templates/pages/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% include 'common/nav.html.twig' %}

  <div  class='no_margin no_padding pic_background padding_50-bottom padding_100-top' style='background: url(" {{ asset('assets/images/wall.jpg') }}") #000033 fixed no-repeat ; background-size: 130% !Important'>
    <div class='transparent_container bg-transparent_black_5'>
    </div>
    <div style='position:Relative' class='clearfix container font-white padding_20-top padding_20-bottom'>

      <div class="row">
        <div class='col-md-7 col-sm-12 mx-auto text-center'>
          <p class="font-sm-4 text-uppercase font-lg-3">Federal Character Commission</p>
          <h1 class="font-weight-900 no_margin-top font-xl-2">Agency Wide Training</h1>
          <p class="font-sm-4 lead mb-5">
            ONLINE SUBMISSION OF NOMINAL ROLL, FORMAT AND PROCESSES
          </p>


          <a href="{{ path('login') }}" class="btn btn-lg top_buffer btn-primary">Apply Now <i class="fa fa-paper-plane"></i></a>
          <a href="#recieve_letter" class='btn btn-lg top_buffer btn-success'>Receive training letter <i class="fa fa-file"></i></a>
        </div>



      </div>
    </div>
  </div>

<div class="mt-2">
    <div class="owl-carousel">
        <div class="item">
            <img src="{{ asset('assets/images/IMG_20171018_121053.jpg') }}" class="img-float">
        </div>
        <div class="item">
            <img src="{{ asset('assets/images/IMG_20171018_121106.jpg') }}" class="img-float">
        </div>
        <div class="item">
            <img src="{{ asset('assets/images/IMG_20171016_115222.jpg') }}" class="img-float">
        </div>
        <div class="item">
            <img src="{{ asset('assets/images/IMG_20171017_164254-2.jpg') }}" class="img-float">
        </div>
        <div class="item">
            <img src="{{ asset('assets/images/IMG_20171016_122040.jpg') }}" class="img-float">
        </div>


    </div>
</div>

    <div class="text-center">
    <a href="" class="btn btn-default font-white mx-auto mt-2 mb-2 font-xs bg-transparent_black_2" style="border-radius:20px"><i class="fa fa-arrow-left"></i> Click and drag left</a>
    </div>

    <script>
        var owl = $('.owl-carousel');
        owl.owlCarousel({
            margin: 10,
            loop: true,
            autoplayTimeout:5000,
            autoplayHoverPause:false,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 2
                },
                1000: {
                    items: 3
                }
            }
        })
    </script>


  <div class="bg-white border_bottom padding_50 no_xs_padding-left no_xs_padding-right no_padding-bottom" id="about_training">

    <div class="container">

      <div class="row">



        <div class="col-md-10 col-sm-12 text-center mx-auto no_padding-bottom">
          <p class="font-xs-2 mb-0 bottom_buffer font-weight-900 text-uppercase font-green">Introduction</p>
          <h1 class='mt-0 mb-5'>About the training</h1>
          <p class=' bottom_buffer font-light text-primary text-justify line-height'>
            The FEDERAL CHARACTER COMMISSION is organising a two - day workshop titled
            "ONLINE SUBMISSION OF NOMINAL ROLL, FORMAT AND PROCESSES"
            scheduled to hold in batches at Chams City, Training Center, Maitama Abuja, Nigeria.
          </p>

          <p class=' bottom_buffer font-sm-2 text-justify font-light text-primary line-height'>
            This workshop is being reorganized to update participants with the emerging trends and best practices as well as to address the observed lapses/challenges found in the submission of some MDAs who had earlier attended a similar workshop with the commission in 2013 It is also to sensitize and train the Desk Officers of the Federal Ministries, Departments and Agencies on the correct Format and Process of forwarding their Nominal Rolls online through the Commission's website/Portal which would ensure smooth and timely submission of their returns.
          </p>

            <div id="recieve_letter"></div>

        </div>

      </div>

    </div>

  </div>


    <div  class='no_margin no_padding pic_background padding_20-bottom padding_30-top' style='background: url(" {{ asset('assets/images/wall.jpg') }}") #000033 fixed no-repeat ; background-size: 130% !Important'>
        <div class='transparent_container bg-transparent_black_8'>
        </div>
        <div style='position:Relative' class='clearfix container font-white padding_20-top padding_20-bottom'>

            <div class="row">
                <div class='col-md-7 col-sm-12 mx-auto text-center'>

                    <h1 class="font-weight-900 no_margin-top font-xl">Receive training letter</h1>
                    <p class="font-sm-4 lead mb-5">
                        If you are the Desk Officer in charge of submitting nominal roll to FCC and your agency have not received any letter concerning the on-going training, please enter your MDA Code to generate/print a softcopy of the letter for further action.
                    </p>
                    <form method="POST">


                        <div class="form-group">


                            <input type="text" name="mda_code" placeholder="Enter MDA Code" onkeypress="return isNumber(event)" required class="form-control form-control-lg">

                        </div>



                        <button class="btn btn-primary">Submit</button>
                    </form>
                </div>



            </div>
        </div>
    </div>



    <div class="bg-green font-white text-center font-black no_xs_padding-left no_xs_padding-right no_padding-bottom padding_30">

        <div class="container">

        <p class="font-xs-2 mb-0 bottom_buffer font-weight-900 text-uppercase font-black">MDAs</p>
        <h1 class='mt-0 mb-5'>How to apply</h1>

      <div class="row">


          <div class="col-sm-4 mb-4">
            <div class="num_count">1</div>
              <p>Obtain the <strong>MDA Establishment Code</strong> from the invitation letter sent to your MDA
              for participation.
            </p>
          </div>

          <div class="col-sm-4 mb-4">
              <div class="num_count">2</div>
            <p>Use the <strong>MDA Establishment Code</strong> to create an account for
              your MDA
              {#<div style="clear: both; font-size: 0.85em; font-style: normal; padding-left: 25px; font-weight:900" class=" "><strong class="text-danger">Note:</strong>
                During MDA registration, please follow the on-screen guide for a quick and easy
                registration.
              </div>#}
            </p>
          </div>

          <div class="col-sm-4 mb-4">
              <div class="num_count">3</div>
            <p>On successful registration, you will be required to <strong>verify and authenticate</strong>
              your account. Please follow the guide(s) you received via <strong>EMAIL</strong> &amp; <strong>SMS
                Message</strong> for the verification process.
            </p>
          </div>


          <div class="col-sm-4 mb-4">
              <div class="num_count">4</div>
            <p>After account creation and verification, you can then proceed to log into your account.
              <div style="clear: both; font-size: 0.85em; font-style: normal; padding-left: 25px; font-weight:900" class=""><strong class="text-danger">Note:</strong>
                Please note that the account registration and verification is done only once for a MDA.
              </div>
            </p>
          </div>

          <div class="col-sm-4 mb-4">
              <div class="num_count">5</div>
            <p>
              On successful login, You can add participants for the training and also select a training
              session to attend.
            </p>
          </div>

          <div class="col-sm-4 mb-4">
              <div class="num_count">6</div>
              <p>
                  Make payment for organization and participants online or by cash at the venue of the training
              </p>
          </div>





      </div>


        </div>

    </div>




    <div  class='no_margin no_padding pic_background padding_20-bottom padding_30-top' style='background: url(" {{ asset('assets/images/wall.jpg') }}") #000033 fixed no-repeat ; background-size: 130% !Important'>
        <div class='transparent_container bg-transparent_black_8'>
        </div>
        <div style='position:Relative' class='clearfix container font-white padding_20-top padding_20-bottom'>

                <h1 class="font-weight-900 no_margin-top text-center mb-5 font-xl">Training Location</h1>

            <div class="row">

                <div class="col-md-9">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7879.318671968691!2d7.494863505079575!3d9.094764882922695!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x104e0a69bb8b562f%3A0x359b684aa41d63a!2sSascon+International+School!5e0!3m2!1sen!2sng!4v1506440288340" width="100%" height="290" frameborder="0" style="border:0" allowfullscreen=""></iframe>
                </div>
                <div class='col-md-3'>


                    <b>Address:</b>
                    <p>
                        ChamsCity, 19a Yedseram Street.
                        Maitama, Abuja.
                    </p>

                    <p>
                        Inside Sascon international School.
                        After the IGP's House.

                    </p>

                </div>



            </div>
        </div>
    </div>


  <div class="d-md-flex">

    <div class="bg-white border_right col-md-6 font-black no_xs_padding-left no_xs_padding-right no_padding-bottom">



      <div class="row">


        <div class="col-sm-10 mx-auto padding_30  no_padding-bottom">
          <p class="font-xs-2 mb-0 bottom_buffer font-weight-900 text-uppercase font-green">Pay</p>
          <h1 class='mt-0 mb-5'>Payment details</h1>



           <p class="mb-4">Please make payment to the following account details provided below:</p>

            <p> Account Name: <br><strong>PYRICH GROUP OF COMPANIES LTD.</strong></p>
            <p> Account Number:<br> <strong>1012835411</strong></p>
            <p> TIN: <br><strong>17780157-0001</strong></p>
            <p> Bank Name:<br> <strong>Zenith Bank</strong></p>



        </div>

      </div>


    </div>


    <div class="bg-white col-md-6 no_xs_padding-left no_xs_padding-right no_padding-bottom" id="recieve_letter">



      <div class="row">


        <div class="col-sm-10 mx-auto padding_30  no_padding-bottom">
          <p class="font-xs-2 mb-0 bottom_buffer font-weight-900 text-uppercase font-green">Training</p>
          <h1 class='mt-0 mb-5'>Available sessions</h1>
          <p class="">
            Below are the currently available sessions in the training to apply for. Each session has a duration of Two (2) days:
          </p>



            {% for session in training_session %}

                <div class="p-3 border bg-gray mb-2">
                {{ session.name }}
                    <p class="m-0 font-xs"><span class="badge badge-primary">DATE</span>: {{ session.startdate|date("l, F j Y") }}</p>
                </div>

            {% endfor %}



        </div>

      </div>


    </div>

  </div>





{% endblock %}

templates/pages/letter.html.twig
{% extends 'access_base_pdf.html.twig' %}

{% block content %}

    {% include 'common/nav.html.twig' %}

    <h2 class="page-header pt-4">MDA letter</h2>
    <hr>


    <button class="btn btn-primary btn-xs mr-2" onclick="printElem('letter');"><i class="fa fa-print"></i> Print</button>


    <div class="padding_50 font-lg" id="letter" style="background-color:#fff !Important; width:100% !Important;font-family: 'Times New Roman' !Important">

        <img src="{{ asset('assets/images/fcc_letterhead.png') }}" style="max-width: 100%" class="mb-5">

        <p class="float-right font-weight-900" style="margin-top: -3px">{{ date }}</p>



    <b>{{ trainings.trainingCode }}</b>

        <div class="clearfix mb-4"></div>

        <p class="m-0">{{ mda.topOfficialDesignation }},<br>
            {{ mda.name }}.</p>
        <div class="row">
            <div class="col-8 m-0">{{ mda.address }}</div>
        </div>



        <div class="clearfix mb-5"></div>

        {% autoescape false %}
            {{ train_letter_continue }}
        {% endautoescape %}


    </div>



{% endblock %}

templates/pages/print_letter.html.twig
{% extends 'access_base_pdf.html.twig' %}

{% block content %}

    {% include 'common/nav.html.twig' %}



    <div class="row mt-4">

    <div class="col-sm-3 list-group">
        {% set count = 0 %}
        {% for mda in all_mda %}
            {% set count = count + 1 %}
            <a href="{{ path('print_mda_letter', { 'id':mda.id }) }}" class="list-group-item">
            {{ count }}. {{ mda.name }}
            </a>

            {% endfor %}
    </div>
        <div class="col-sm-9">

            <h2 class="page-header pt-4">{{ mda.name }} letter</h2>
            <hr>


            <button class="btn btn-primary btn-xs mr-2" onclick="printElem('letter');"><i class="fa fa-print"></i> Print</button>


            <div class="padding_50 font-lg" id="letter" style="background-color:#fff !Important; width:100% !Important;font-family: 'Times New Roman' !Important">

                <img src="{{ asset('assets/images/fcc_letterhead.png') }}" style="max-width: 100%" class="mb-5">

                <p class="float-right font-weight-900" style="margin-top: -3px">{{ date }}</p>



                <b>{{ trainings.trainingCode }}</b>

                <div class="clearfix"></div>


                <p class="m-0">{{ mda.topOfficialDesignation }},<br>
                    {{ mda.name }}.</p>
                <div class="row">
                <div class="col-8 m-0">{{ mda.address }}</div>
                </div>




                <div class="clearfix mb-5"></div>

                {% autoescape false %}
                    {{ train_letter_continue }}
                {% endautoescape %}


            </div>


        </div>

    </div>





{% endblock %}